version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
      - ./php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9090:9090"
    depends_on:
      - db
    stop_grace_period: 600s

  nginx:
    image: nginx:latest
    ports:
      - "8083:80"
    volumes:
      - .:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/snippets:/etc/nginx/snippets
    depends_on:
      - php
    stop_grace_period: 600s

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
    command: "postgres -c shared_preload_libraries=pg_stat_statements,unaccent"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
