version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "9090:9090"
    networks:
      - app-network
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - "8083:80"
    volumes:
      - .:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/snippets:/etc/nginx/snippets 
    depends_on:
      - php
    networks:
      - app-network
    
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password 
      MYSQL_DATABASE: yii_manage
      MYSQL_USER: yii_manage 
      MYSQL_PASSWORD: yii_manage
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "33063:3306"

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
